In [184]:
grid=[[0,0,0,3],
      [4,0,0,0],
      [0,0,0,1],
      [3,0,0,0]]

In [185]:
import numpy as np

In [186]:
def test(y,x,num):
    global grid
    for i in range (0,4):                 # to check in the same column
        if grid[y][i] ==num :
            return False   
        
    for i in range (0,4) :                #to check in the same row 
        if grid[i][x] ==num :
            return False
    
    
    x_box=(x//2)*2
    y_box=(y//2)*2
    
    for i in range (0,2):
        for j in range (0,2):
            if grid[y_box+i][x_box+j]== num:
                return False
            
    return True       

In [187]:
def solveMatrix() :
    global grid
    for y in range (0,4) :
        for x in range (0,4):
            if grid[y][x] == 0 :
                for num in range (1,5):                
                    if test(y,x,num) :
                        grid[y][x]=num
                        solveMatrix()
                        grid[y][x]=0
                return       
                
            
    print(np.matrix(grid))
                    

In [188]:
solveMatrix()

[[1 2 4 3]
 [4 3 1 2]
 [2 4 3 1]
 [3 1 2 4]]
