In [1]:
grid=[[8,0,0,0,0,0,0,0,0],
      [0,0,3,6,0,0,0,0,0],
      [0,7,0,0,9,0,2,0,0],
      [0,5,0,0,0,7,0,0,0],
      [0,0,0,0,4,5,7,0,0],
      [0,0,0,1,0,0,0,3,0],
      [0,0,1,0,0,0,0,6,8],
      [0,0,8,5,0,0,0,1,0],
      [0,9,0,0,0,0,4,0,0]   
]


In [2]:
def test(y,x,num):
    global grid
    for i in range (0,9):       # to check in the same column
        if grid[y][i] ==num :
            return False   
        
    for i in range (0,9) :      #to check in the same row 
        if grid[i][x] ==num :
            return False
    
    
    x_box=(x//3)*3
    y_box=(y//3)*3
    
    for i in range (0,3):       #to check in the 3*3 block 
        for j in range (0,3):
            if grid[y_box+i][x_box+j]==num:
                return False
            
    return True     

In [3]:
import numpy as np

def solveMatrix() :
    global grid
    for y in range (9) :
        for x in range (9):
            if grid[y][x] == 0 :
                for num in range (1,10):                
                    if test(y,x,num) :
                        grid[y][x]=num
                        solveMatrix()
                        grid[y][x]=0
                        
                return
            
    print(np.matrix(grid))

In [4]:
solveMatrix()

[[8 1 2 7 5 3 6 4 9]
 [9 4 3 6 8 2 1 7 5]
 [6 7 5 4 9 1 2 8 3]
 [1 5 4 2 3 7 8 9 6]
 [3 6 9 8 4 5 7 2 1]
 [2 8 7 1 6 9 5 3 4]
 [5 2 1 9 7 4 3 6 8]
 [4 3 8 5 2 6 9 1 7]
 [7 9 6 3 1 8 4 5 2]]


In [1]:
# In this My code sucessfully solves the world toughest sodoku as proclaimed by https://www.conceptispuzzles.com/index.aspx?uri=info/article/424 